xuyangzo/Bloggy

.gitignore
README.md
package.json
public/server/models/Post.js
public/server/models/User.js
public/server/routers/api/posts.js
public/server/routers/api/users.js

User Comment/Following/Subscribe

User Comment/Following/Subscribe

---

package.json
public/client/src/components/common/LoginNavbar.js
public/client/src/components/indexPage/Bloggy.js
public/client/src/components/indexPage/Header.js
public/client/src/components/indexPage/IndexBody.js
public/client/src/components/viewPage/Comment.js
public/client/src/components/viewPage/View.js
public/client/src/styles/partials/_viewPost.scss
public/server/models/Post.js
public/server/routers/api/posts.js

Index Page Scroll, View Page Comment

Index Page Scroll, View Page Comment

---

public/client/src/components/viewPage/Comment.js
public/client/src/components/viewPage/Thumb.js
public/client/src/components/viewPage/View.js
public/client/src/styles/partials/_mixin.scss
public/client/src/styles/partials/_viewPost.scss
public/server/models/Post.js
public/server/routers/api/posts.js

View Page Update, Toggle Comments

View Page Update, Toggle Comments

---

public/client/src/components/indexPage/IndexBody.js
public/server/routers/api/posts.js

Masonry Format

---

package.json
public/client/src/components/indexPage/Header.js
public/client/src/components/indexPage/IndexBody.js
public/client/src/components/indexPage/LoginHeader.js
public/client/src/components/viewPage/Comment.js
public/client/src/components/viewPage/View.js

Index Page Animation, Comment Bug Fix

Index Page Animation, Comment Bug Fix

---

package.json
public/client/src/components/viewPage/Comment.js
public/client/src/components/viewPage/Thumb.js
public/client/src/components/viewPage/View.js
public/client/src/styles/partials/_indexGrid.scss
public/client/src/styles/partials/_viewPost.scss

View Page Pagination, front-end like/dislike

View Page Pagination, front-end like/dislike

---

package.json
public/client/src/components/common/LoginNavbar.js
public/client/src/components/viewPage/Comment.js
public/client/src/components/viewPage/View.js
public/client/src/components/viewPage/ViewHeader.js
public/client/src/styles/partials/_loginNavbar.scss
public/client/src/styles/partials/_viewPost.scss
public/server/models/Post.js
public/server/routers/api/posts.js
public/server/routers/api/users.js

Header bug Fix, View Author Update

Header bug Fix, View Author Update

---

public/client/src/components/common/DeleteModal.js
public/client/src/components/common/LoginModal.js
public/client/src/components/common/LoginNavbar.js
public/client/src/components/viewPage/Comment.js
public/client/src/components/viewPage/Thumb.js
public/client/src/components/viewPage/View.js
public/client/src/styles/partials/_modal.scss
public/client/src/styles/partials/_viewPost.scss
public/client/src/styles/style.scss

Delete Post, Modals

---

public/client/src/components/common/DeleteModal.js
public/client/src/components/viewPage/Thumb.js
public/client/src/components/viewPage/View.js

Delete Bug Fix

---

public/client/src/components/indexPage/Bloggy.js
public/client/src/components/postPage/Editor.js
public/client/src/components/utils/Loader.js
public/client/src/components/viewPage/Thumb.js
public/client/src/components/viewPage/View.js
public/client/src/styles/partials/_loader.scss
public/client/src/styles/partials/_viewPost.scss
public/client/src/styles/style.scss

Edit, Middle of Page Bug Fix

---

public/client/src/components/viewPage/Comment.js
public/client/src/components/viewPage/View.js

Thumb Bar Bug Fix

---

public/client/src/components/postPage/Editor.js
public/client/src/components/viewPage/Thumb.js
public/client/src/components/viewPage/View.js
public/client/src/styles/partials/_viewPost.scss
public/server/models/Post.js
public/server/models/User.js
public/server/routers/api/posts.js

Edit Bug Fix, Favorite

---

public/client/src/components/common/LoginNavbar.js
public/client/src/styles/partials/_loginNavbar.scss
public/client/src/styles/style.scss
public/server/routers/api/users.js

Profile Image Hover

---

.example.env
.gitignore
README.md
package.json
public/server/config/keys.example.js
public/server/config/passport.js
public/server/routers/api/posts.js
public/server/routers/api/search.js
public/server/server.js

.env, README

---

public/server/routers/api/users.js

.env bug fix

---

public/client/src/components/viewPage/View.js

Log out bug fix

---

public/client/src/components/common/LoginNavbar.js
public/client/src/components/postPage/Editor.js
public/client/src/styles/partials/_editor.scss
public/client/src/styles/partials/_loginNavbar.scss
public/server/routers/api/posts.js

Get posts router

---

public/client/src/components/postPage/Editor.js
public/server/routers/api/posts.js

Editor Update

---

public/client/src/components/postPage/Editor.js
public/client/src/components/viewPage/View.js
public/server/models/Post.js
public/server/routers/api/posts.js

Delete Image and Edit Post

---

package.json

trigger build

---

package.json
public/server/server.js

add prerender.io

---

public/client/src/components/indexPage/Header.js

fix header image

---

public/server/server.js

fix router when doing deployment

fix router

---

public/server/server.js

fix refresh issue

---

public/server/server.js

try to fix refresh issue

---

public/server/server.js

fix parenthesis

---

package.json
public/index.html
public/server/server.js
webpack.config.js

webpack optimization

---

public/server/server.js

change server static assets path

change server static assets path

---

public/client/src/components/profile/Favorite.js
public/client/src/components/profile/Profile.js
public/client/src/components/profile/ProfileContent.js
public/client/src/styles/partials/_favorites.scss
public/client/src/styles/style.scss
public/index.html
webpack.config.js

webpack config fix + favorite page setup

webpack config fix + favorite page setup

---

index.html
package.json
public/client/src/components/profile/Favorite.js
webpack.config.js

webpack bug fix
